### ISSUE TITLE
libxo text output to stdout cannot be piped to more/less

### ISSUE THREAD

**Issue by psjm3** [CTSRD-CHERI/chericat#25]
- chericat | more ==> works
- chericat -f existing.db -v | more ==> no output
- chericat --libxo xml -f existing.db -v | more ==> works
- chericat --libxo json -f existing.db -v | more ==> works

**Comment by psjm3** [comment]
adding 
xo_set_style(NULL, XO_STYLE_JSON) ==> works when pipe to more
but
xo_set_style(NULL, XO_STYLE_TEXT) ==> no output when pipe to more

**Comment by InterestedInTechAndCake** [comment]
Fixed in https://github.com/CTSRD-CHERI/chericat/pull/26
