### ISSUE TITLE
chericat needs a license

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/chericat#6]
The overall project needs a license in a LICENSE.txt file. Likewise individual c and python source files need a license or at least an SPDX header. Most likely it should a BSD license source tree the long-term desire to incorporate some of chericat's functionality into procstat.

**Comment by rwatson** [comment]
The baseline chericat work was supported by the EPSRC CHaOS project, and should use this license:

https://github.com/CTSRD-CHERI/cheri-licenses/blob/main/chaos/chaos-bsd-style-license.c

**Comment by InterestedInTechAndCake** [comment]
I can't view the cheri-licenses repo for some reasons, clicking the link above returns a 404 and when I searched from CTSRD-CHERI it didn't find anything.

**Comment by brooksdavis** [comment]
> I can't view the cheri-licenses repo for some reasons, clicking the link above returns a 404 and when I searched from CTSRD-CHERI it didn't find anything.

Hopefully fixed once you accept the invite to join the CHERI group
